language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.3
  - 3.4
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
install:
  - pip install -q $DJANGO
  - pip install -e .
  - pip install pytest pytest-django
script:
  - python setup.py test
