language: python
sudo: false
branches:
  only:
    - master
python:
  - 2.7
  - 3.3
  - 3.4
  - "pypy"
  - "pypy3"
env:
  - DJANGO="Django>=1.7,<1.8"
  - DJANGO="Django>=1.8,<1.9"
before_script:
  - psql -c 'CREATE DATABASE travis_postgis;' -U postgres
  - psql -c 'CREATE EXTENSION postgis;' -U postgres -d travis_postgis
  - psql -c 'CREATE EXTENSION postgis_topology;' -U postgres -d travis_postgis
install:
  - pip install -q $DJANGO
  - pip install -e .
  - pip install psycopg2cffi coveralls
  - if [[ "$TRAVIS_PYTHON_VERSION" != pypy* ]]; then pip install psycopg2; fi
script:
  - coverage run --source django_fakery setup.py test
after_success:
  coveralls
